### ISSUE TITLE
Remove Crate Patches from `Cargo.toml` Upon Solana Crate Updates

### ISSUE THREAD

**Issue by tareknaser** [hyperledger/solang-aqd#5]
Presently, there are dependency conflicts between `solana` crates and `contract-extrinsics`, which are reflected in [this issue (#26688)](https://github.com/solana-labs/solana/issues/26688) within the Solana repository.
A simplified `Cargo.toml` configuration for `solang-aqd` includes these dependencies:

```toml
[dependencies] 
contract-extrinsics = {git = "https://github.com/paritytech/cargo-contract"} 
solana-client = "1.17.1"
```

However, this setup leads to an error due to conflicting dependencies, specifically related to the `zeroize` crate, which causes version conflicts.

As a temporary fix, `solang-aqd` includes a patch in its `Cargo.toml` to address these conflicts:

```toml
[patch.crates-io.aes-gcm-siv]
git = "https://github.com/RustCrypto/AEADs"
rev = "e1e35e0c4f4943da0a99ceb8477c421dcfae2c33"
```

Solana plans to solve this issue soon, as outlined in [this related discussion](https://github.com/solana-labs/solana/pull/33853#issuecomment-1781911376). 
Once Solana resolves this issue, the patches in `solang-aqd`'s `Cargo.toml` should be removed.
